break_into_partial_movies: false
camera_resolutions:
  4k: 3840x2160
  default_resolution: low
  high: 1920x1080
  low: 854x480
  medium: 1280x720
directories:
  mirror_module_path: false
  output: ~/code/media
fps: 30
full_screen: false
style:
  background_color: "#333333"
  font: Consolas
  tex_template: default
universal_import_line: from _manim.manimlib import *
window_monitor: 0
window_position: UR
